import '/imports/startup/server/Accounts';
import '/imports/startup/server/Publications';
import '/imports/startup/server/Mongo';
import '../imports/api/event/EventCollection.methods';
import '../imports/api/forum/ForumPostCollection.methods';
import '../imports/api/user/UserCollection.methods';
import '../imports/api/user/UserEventCollection.methods';
import '../imports/api/report/ReportCollection.methods';
import '../imports/api/notification/NotificationCollection.methods';
